
export const repositoryConstant = {
    GET_REPOSITORY_REQUEST: "GET_REPOSITORY_REQUEST",
    GET_REPOSITORY_SUCCESS: "GET_REPOSITORY_SUCCESS",
    GET_REPOSITORY_FAILED: "GET_REPOSITORY_FAILED",
   
    ADD_REPOSITORY_REQUEST: "ADD_REPOSITORY_REQUEST",
    ADD_REPOSITORY_SUCCESS: "ADD_REPOSITORY_SUCCESS",
    ADD_REPOSITORY_FAILED: "ADD_REPOSITORY_FAILED",
   
    UPDATE_REPOSITORY_REQUEST: "UPDATE_REPOSITORY_REQUEST",
    UPDATE_REPOSITORY_SUCCESS: "UPDATE_REPOSITORY_SUCCESS",
    UPDATE_REPOSITORY_FAILED: "UPDATE_REPOSITORY_FAILED",
   
    DELETE_REPOSITORY_REQUEST: "DELETE_REPOSITORY_REQUEST",
    DELETE_REPOSITORY_SUCCESS: "DELETE_REPOSITORY_SUCCESS",
    DELETE_REPOSITORY_FAILED: "DELETE_REPOSITORY_FAILED",
};

export const recentlyOpenConstant = {
    GET_RECENTLY_REPOSITORY_REQUEST: "GET_RECENTLY_REPOSITORY_REQUEST",
    GET_RECENTLY_REPOSITORY_SUCCESS: "GET_RECENTLY_REPOSITORY_SUCCESS",
    GET_RECENTLY_REPOSITORY_FAILED: "GET_RECENTLY_REPOSITORY_FAILED",
    
    UPDATE_RECENTLY_REPOSITORY_REQUEST: "UPDATE_RECENTLY_REPOSITORY_REQUEST",
    UPDATE_RECENTLY_REPOSITORY_SUCCESS: "UPDATE_RECENTLY_REPOSITORY_SUCCESS",
    UPDATE_RECENTLY_REPOSITORY_FAILED: "UPDATE_RECENTLY_REPOSITORY_FAILED",
}

export const securityConstant = {
    GET_SECURITY_QUESTION_REQUEST: "GET_SECURITY_QUESTION_REQUEST",
    GET_SECURITY_QUESTION_SUCCESS: "GET_SECURITY_QUESTION_SUCCESS",
    GET_SECURITY_QUESTION_FAILED: "GET_SECURITY_QUESTION_FAILED",
    
    UPDATE_SECURITY_QUESTION_REQUEST: "UPDATE_SECURITY_QUESTION_REQUEST",
    UPDATE_SECURITY_QUESTION_SUCCESS: "UPDATE_SECURITY_QUESTION_SUCCESS",
    UPDATE_SECURITY_QUESTION_FAILED: "UPDATE_SECURITY_QUESTION_FAILED",
    
    VALIDATE_SECURITY_QUESTION_REQUEST: "VALIDATE_SECURITY_QUESTION_REQUEST",
    VALIDATE_SECURITY_QUESTION_SUCCESS: "VALIDATE_SECURITY_QUESTION_SUCCESS",
    VALIDATE_SECURITY_QUESTION_FAILED: "VALIDATE_SECURITY_QUESTION_FAILED",

}

export const folderDataConstant = {
    GET_FOLDERS_Request : "GET_FOLDERS_Request",
    GET_FOLDERS_SUCCESS : "GET_FOLDERS_SUCCESS",
    GET_FOLDERS_FAILED : "GET_FOLDERS_FAILED",

    ADD_FOLDERS_Request : "ADD_FOLDERS_Request",
    ADD_FOLDERS_SUCCESS : "ADD_FOLDERS_SUCCESS",
    ADD_FOLDERS_FAILED : "ADD_FOLDERS_FAILED",
    UPDATE_UPLOAD_PROGRESS: 'UPDATE_UPLOAD_PROGRESS', // Define the constant for updating progress
    
    DELETE_FOLDERS_Request : "DELETE_FOLDERS_Request",
    DELETE_FOLDERS_SUCCESS : "DELETE_FOLDERS_SUCCESS",
    DELETE_FOLDERS_FAILED : "DELETE_FOLDERS_FAILED",
}
export const commitConstant = {
    GET_COMMIT_Request : "GET_COMMIT_Request",
    GET_COMMIT_SUCCESS : "GET_COMMIT_SUCCESS",
    GET_COMMIT_FAILED : "GET_COMMIT_FAILED",
}
export const contributorsConstant = {
    GET_CONTRIBUTORS_Request : "GET_CONTRIBUTORS_Request",
    GET_CONTRIBUTORS_SUCCESS : "GET_CONTRIBUTORS_SUCCESS",
    GET_CONTRIBUTORS_FAILED : "GET_CONTRIBUTORS_FAILED",
}
export const CodeFrequencyConstant = {
    GET_CODEfREQUENCY_Request : "GET_CODEfREQUENCY_Request",
    GET_CODEfREQUENCY_SUCCESS : "GET_CODEfREQUENCY_SUCCESS",
    GET_CODEfREQUENCY_FAILED : "GET_CODEfREQUENCY_FAILED",
}
export const fileDataConstant = {
    GET_FILEDATA_Request : "GET_FILEDATA_Request",
    GET_FILEDATA_SUCCESS : "GET_FILEDATA_SUCCESS",
    GET_FILEDATA_FAILED : "GET_FILEDATA_FAILED",
}

export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",
  };

export const userContants = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
};
// export const commit constant = {
//     USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
//     USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
//     USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
// };
